/**
   * Removes the Google Gemini AI sparkle watermark using reverse alpha blending.
   *
   * The Gemini watermark is a semi-transparent white sparkle star composited
   * at a fixed position relative to the bottom-right corner. The exact alpha map
   * was extracted by comparing watermarked vs clean pairs of real Gemini images.
   *
   * Blending formula:  blended = original * (1 - a) + 255 * a
   * Reversal formula:  original = (blended - 255 * a) / (1 - a)
   *
   * Position (verified by pixel-diff analysis):
   *   Large images (max(W,H) > 1024):  96x96 at padding=64 from each edge
   *   Small images (max(W,H) <= 1024):  48x48 at padding=32 from each edge
   */

  const ALPHA_96_B64 = 'BAIDAwMDAwQAAwMEAwEFAQECAAIAAAEBAwECBAEDAwMCAwMBAwIAAQEBAQEBATh4cToBAwACAQEDAwEEAgIEAgIDAQQEAwICAQICAgECAwMCAgMDAgIDBAMDAgIEBQQEAwMCAwEDAwMBAQMDAQEDAwECAQEAAAAAAQEDAwEDAwEDBQMDAQAAAAEAAAABD4CAgIEJAgAAAQICAgIBAQEDBAICAQEBAgIBAgACAAEBAwMDAwMDAgIDAgMDBgUEBQQFAQABAQIDAwIAAQEDAQEAAAECAQAAAAABAQAAAQECAQMDBAMDAAEAAQAAAQIBKYB/gX8xAAABAgEAAAEBAQUEAwQEAQABAQIDAwMCAgUCAQIDAwMDAwQEBAMBBAMEBAMDAAEBAQEFAQIAAQECAAAAAQIBAAEAAAEAAQIBAQABAwMBBAEBAAEAAAABAgIDUoCAgYBPAQEBAQEAAAEBBAQDAQMEBAEBAgICBAQCAwIEAQIEBQQBAQMDBQQDAwMFBAMDAAABAwUEBAIBAQEBAAADAAMDAAIAAQABAAEAAAABBAMBAQIBAQEEAgABAAEDcoCAgIB4AQMBAgIBAQIDBAQEAwQEAgEBAQIDBQQEBAQEBAMDAwEAAwEDBAMDAgUDBQMDAQACAwIEBAQDAQQDAAAAAAIDAgAAAQEBAQEBAAEBBAQEBAEDBAIDAAIDAgIggICAgIB/IQEBAQICAQEBAwQDAwMEAgEBAQICAwQEBAQDAQMDBAEBAwQDAwMDAwQDBAMDAQEBAQMDAwMEAwABAAEBAAADAAABAwMDAwIAAQIDAQEBAgIBAwIAAgACAgJSgH+AgICASQEBAQEEAgEBAQEDAwUDAwEBAwEDAwMDBAMBAQMCAwEDAQMFBQQEAwMDAwIDAQMCAgMDAQQEAgIBAQMEAAAAAQMDAwECAwACAgICAQECAQAAAAAAAQABAgFwgICAgIB/eAECAQEEAgMEAwEDAQICAQEBAQIBAwQDAgQBAQMDAQMEAwQDBQUEBAQDBAMCAwICAgEBBAIBAwEDAQEEAAABAwQBAgICAgABAgIDAgMEAwEAAAACAAMDAymAgYB/gYGAgCEDAgADAwECAwMDAwECAQEBAQEDAwEEAQEAAQEEAwMEAwEEBgMCAgMEBAQEAQMBAQABAgEBAwECAQMBAQACAwMCAwABAAICAgICAQEDAwAAAAAAAAIDA1iBgICAgYF/f2ABAAADBAQDAwICAgICAAAAAgIDAQMCAwAAAQECBAMDAwMFAwIDAwMDBQMDAwIDAwEBAQEDAwECAAAAAQMDAgMBAQEBAAMCBAEBAQMDAwABAAEAAAEEEX9/f39/f4F/f38QAAEBAQMAAQEBAAAAAAMAAAABAQABAQEDAwMDAwMCAwMDAgMDAgQBAwEDAwEDAwEBAQECAwEBAQAAAQMDAgIBAwEAAQQDAgICAwMCAwEBAQAAAAICUH9/f3+Bf4B/f39CAQEAAAEEAwQBAQEBAAIAAAMCAgMAAQAEBAQDAwICAwMBAgACAQMDAwMFAAABAQABAQEBAAAAAQMAAgECAQADAwMAAAECAgMDAwIAAAIAAgAAAQARgYF/f39/f4F/f394CAAAAQEBAQECAQACAQEBAAMDAwEAAQAEAwICAQMDAgMEBAMEBAUDAwMDAQEAAQEAAQICAQABAwMBAgECAQICAwAAAAEDAgMCAwMCAQAAAAEAAQNBf4F/f39/gYGBf39/QAICAgEEBAQBAQEBAgEAAgQDBAMBAAAAAgIDAgICAQIDAwIDAwUDAwMDAQEBAQIEAQEAAQABAwMCAQECAgEDAwAAAQIDAwMDAwMAAAAAAAAEBBJwgYF/f3+BgYGBgYF/eAkBBQQEAwEEBAECAgQAAwMDBAICAgECAwMEBAMDBAQEBAUGAwIDAwMDAQMBAgMFAwABAAAAAQACAQMDAgIDAQEBAgIDAQIDBAMBAAABAQEDBFKBgYF/f4GBgIKAgIGBgUEDAQMEAgMFAwEAAAICBAMEBAEBAQMDAwMDAwMDBQYDAwIFAwMDBQMDAgICAwMDBQMBAQAAAgEEBAMDAgMBAQECAwIDAQADBAQBAwEDAAEDEoGBgYGBgH+AgICAgYGBgHgRAwMCAwIDBAMCAQMBAwMDAgIBAgIDAwIAAwMDAwMDAwMDAwMCAwMBAQIDAwUEAwMCAQAAAgEDBAMDAAIDAwIDAQEAAAEDAAABBAQDAwMBUYF/gYCAgYF/gICBgX+BgIBYAwICAgMDAgIBAQMDAQADAQACAwMEBAMCAwIDAwMDBQMDAwIDAwMDAQIDAwEBAwMDAQABAAEDBQQDAQMBAQEDBAIDBAMBBAQDAwQDAwMpf4F/gH9/gIOBgICAgIGBf4CBIQEAAQQBAQECAAICAgICAwIDAgMDBAMDAwMDAwICAgMDAQMBAwQCAQMDAgMDAgMEBQMCAQADBAMDAAIBAAEDAQEABAECAAEDAwIDAwNwgYCBgICAgIGAgICBgYCAgH+BcQkDAgMBAQEAAQIDAwICAwIDAwIDAwMDAwMDAwIBAgIDBAMDAwEBAwMDAQEDAQIBAgMBAgEBAgICAgMAAQMEAwMEAwEBAAABAQEDBEF/gYCAgICAgICAgIGBgX+AgIGAgEgBAwMBBAEBAQEDAwIDAgMCAwMDAQMEBAEEBQMBAwABAQEBBQEBAwMBAwIDAQIBAgICAgICAQMBAgAAAQMDAQQDAQICAQECAAMEG4GBgIB/gIB/gICAgYGBgYGAgH+CgYAhAwMDBAIBAgICBAIEBAMBAwMDAwMFAwMDAwMDAQEBAgQEBAMBAwMBAQABAAECAgEAAAAEAwICAgADAwMCAwMAAAIDBQIAAAIQcYGAgIGBgICAgICBgYGCgYGAgYGBgYBxCwQEBQMBAAEDAwMDAwMDAwIEAwMDBAIDAgMDAwIDAwQCAwEBAwMAAAABAAAAAQAAAAEDAwIAAgICAwEDAwMDAgIDAgIBAgJRf4CAgIGAgIGAgIGBgIGAf4GAf4GBgYGBWAMDBAMDAQEDBAEEAwQEAwMEBAMCBAMDAgMBAQQEAwIBAgMBAwMAAAABAwMAAQEBAAABAgABAwIBAAEDAwMAAgICAwADAkKBgICAgYGBgIGBgICAgX+Bf3+Bf3+BgYGBfzkBAAQEAAMEAQMABAQEAwMDAwMDAwMFAgMDAgMCAgQBAgIAAgAAAAABAgIDAAAAAAEAAAAAAwMBAQIDAwQAAAEAAAECI4F/gICAf4GBgYKAgYGBf39/gX9/f39/gYKBf38fAAQEAQEEAAEEAwQEAAQEBAQBBAMDBAQDAwMEAwMAAwACAAEBAQICAgMDAwEAAAECAAIDAAABAAACAwIDAQAAAwEQeYF/f4CAgICAf4CBgYGBf4F/f4GBf3+Bf4F/f393EgEDAQEBAQABBAQBAQQEAwMDAwMDAQEDAAMDAQMDAwQDAgEAAAIBAwMCAgACAQAAAQEDAgIBAgADAwMAAAAAAA9vf39/f39/f4CBf3+BgYF/gYF/gYGBf39/gX+Bf4B/cRADAAAEAwEBAAMAAQMEBAMDBAEEAwMDBAMBAwMDAwQBAwEAAAEEAgMBBAEBAQEAAQMDAwIAAAMBAwAAAAEDEXF/f39/f39/f4GBgX+BgYGBgX9/f4F/f39/gX+Bf39/gXAPAAAEAwEBAQMBAgMEBAMDAwMEAwEBAwQEAwMDAwEBAwICAgMEAwICAgEBAQEBAgICAwMAAgIBAAEAAQEKcYF/gX9/f39/f4GBgYGBgX+Cf3+Bf3+Bf4F/gX9/f3+BgYFpCAMBBAAAAAMBAQEEAwMDAQMDAwEBAwQDAwMDAwEBAwABAQMCAwMBAQIAAQICAgMDAwICAQABAAABARJqf39/gX9/f4GBgYGBgX9/gYF/gYF/gYGBf3+BgX9/f3+BgYGBcRQEBQEBAAEDBAMABAQBAQEDAwQDBAQEBQMDBAABAwIBAQIDAgEBAwICAgMCAQMDAQMBAwEDAQEAEXGBgX9/gX9/gX+BgYGBgX+BgX+Bf4GBgYKCgIGBgX9/f3+AgYF/f3AQAQAAAwEDAwMDAwMBAQEBAwQEBAMEBAQDAwEDAwMAAQIDAAEAAwIBAgMCAQEBAQIDBAEBAQERcYGBgn9/gX+BgYGBgYGBf3+BgYGBgYGBgYGBgYGAgX+AgICBgICAgIBxDwEBAQIDBQMDAwQBAQMBAwQBAwQEAwQEBAEBAwMBAAMDAQEBAwMCAwMEAwEBAAICBQMAASJ5gIGBgn9/gICAgICAgICAgIB/gH+BgICAgYGBgIGAf39/f4CAgIGAgYCAeCEBAQEBAgMDAgIBAgIDAwMCAwMDAwMDAgIDBgUAAgMCAQECAgICAgMDAgEAAQIDAwMAOYGBgIB/gICAgICAgICAgICAgH+AgH9/gX9/gICAgIGBgX9/f4F/gICBgICAgH9AAgICAwEEAwEBBAQEAwMEBAMDAgIBAwYFAwIAAQQDAQIBAwIBAgMBAgIBAQICAwdXf4CAf4CAgICBgICAgICAgICAgIF/f3+AgH+AgIGAgYGBgX9/f4GBf3+AgH+BgH9/URIDAwMDAwQEBAQEBAQDAwQFAwMDBAMFAgIBAQEBAQMBAQMBAQMDAwMCAAIDIXCAgIGAf4CAgICAgYCAgICAgICAf4CAgH+Bf4GAgYGBf4GBgX9/f39/gX9/gIF/f4CAgHEaAwEDAgEEAwIDAgEDAwQEAwMDAgICAQEBAQABAwIBAQMFBAMDBAICAghJgICAgICAgICAgICAgICAgICBgIGBgICAgYGBgICAgYGBf39/gYGBgIGBf39/gICBgYCAgICAQgMCAQIEAwMDAgIEAwQCAwMCAwEAAwUCAQACAQMBAwMEAwQCAwMDIXCAgICAgYGAgICBgIGAgICAgIGBgIGBgIB/gIGBgYGAgICAgICAgYGBgYGBgX+AgICBgICAgICAgHIqAgMDAwMCAwMDAgQDAwMBAQEBAwMCAQECAQMDAwMFAQEDAxBYgIGBgH+AgYGAgICBgICAgICAgYGBgYGBf4B/goGCgoGAgICBgICAgICBf4F/gYGAgICAgYCBgYGAgIGBURADAwMDBAMDAwMDAwMBAwEDBgMCAwEBAQICAwMDAgIHQXiBgICAgH+AgYCAgICAgYCBgICBgYGAgIB/gICAgYGBgICAgICAgICAgIF/f3+AgIGAgICBgYB/gYGBgIKBgYFSEQIFAwMEAwMDAwMDAwQEAwQCBAECAwMCAwICCUJ4gIGAf4CAgICAgIGAgIGAf4CBgICBgYCAgICAf4CAf3+BgYCAgICAgICAgYGAgICAgIGBgICAgIB/gYGAgIGCgIGAcEISBAQDAwMDAwMDAwQFAwIBAAIDAgIBAg9BeYCAgICAgICAgICAgIGAgIGAgICAgICAgYCAgIB/f3+AgX+BgYGAgYCAgICAgYGBgICAgICAgICAgICAf4GAgICAgYGBgX+BUREBBAEDAQICAgIDAQEBAwIEAQEgYICAgIGBgICAgICAgICAgYGAgICBgICAgICAgYCAgIB/gICAgICBgYKAgoGAgYGBgYF/gICAgICAgICAgIB/f4CBgYB/gYGBgYGBgYFXKAMDAQMCAwMDAQMCAgEgSHmAgICAgICBgICAgICAgICAgICAgICAgIGAgH+AgICAgYCBf4CBgYGBgYCBgYGAgYGBgICAgICAgICBgICAgICBgYF/gX+BgYF/gYF/f3+AgnBQIwQEAgMDAwoxUXmAgICAgICAgIGBgIGBgICAgIKBgYGAgYCAgIGBgYCAgIGBgoGBgICBgoGBgICAgICBgYGBgICAgICAgIGBgICAgICBgX9/f4GBf4GBgYGBf4CBgYCCgXJSKhICOoGBgYCBgYGBgYCBgoCAgYCBgYGBgYGCgIGAgICBgYGBgYCAgH+AgYGBgIF/gIGBgICAgICAgIF/gICBgYGAgIGAgICAgH+BgX9/f3+BgYGBf39/gIGAgYGBgYGAgYA5cIGBgYKBgYGBgYGBgYKBgYCBgoCBgYGBgIGAgICAgYGCf4CAgICBgIGBgIGBgYGAgICAgICAgIGBgICAgICAgIGBgICAf4GBgYF/f3+BgYGBgYGAgYCAgYGAgYGAgIB4eIGBgYGBgICAgYCAgICAgICAgICBgYCAgYCAgICBgYGAgICAgICAgIGAgICBgYGBgICAgYGBgICAgYCAgICAgIGAgIGAgYF/gYGBgICAgICBgYGAgIGAgIGBgIGBgYByOn+AgICAgICAgYCBgIGAgICAgICBgYCAgICAgICBgYCAgICAgoCAgYCAgICAgICAgYGBgYGAgICAgYGAgICAgICAgICAgoGAgICBgICAgICBgICBgYCAgYF/gYGBgIE6AxUoUXCAgICAgIGAgICAgYCAgICAgICAgICAgICAgICAgICAgH+AgIGBgICAf4CAgYCBgYCAgICAgICBgYGAgIGAgICAgIGBgYGAgYCAgYCBgYGAgICBgX+BgHlQMAkBAwQCAwIhT3CAgICAgICBgICBgICAgICAgICAgICAgICAgIGAgYGAgICAgH9/gICAgIGAgYCAgICAgYGBgYCAgIGAgICBgYGBgYGBgYCAgYGBf4GAgIGBgXhJIQQDAQEBAwMCAAIBAgIpWYCAgYCBgICAgICAgYCAgIGBgICAgYCBgIGBgYGBgYCCgICAgYCAgICAgIGAgICAgYGBgYGBgYGBgICAgIGBgYGBgYGBgYGBgYCAgYFhIQQFAwIBAQEBBAQDAwICAgIDAxBRgICAgoKAgIGBgYCBgICBgIGAgIGBgIKBgYGBgoKBgICAgYCAgYCAgIGAgICAgIGBgYGBgYGAgICAgIGBgYGBgIGBgYGAgYB5QhMDAwUGAwMBBAEBAwICAwUDAwMDAwICEkFwgYGBgIGCgYCAgYGBgYGBgYGBgICBgIGBgoGBgYCAgICAgIGBgIGAgICAgYCBgYGBgYGBgICAgYGBgYGAgYGBgYGBeUEJAgICBAQFAwEEAgEBAwIDBAUDAgMFBQIDAgMPUICAgIGCgoGBgYKBgYGBgYGBgICBgICBgYGBgYCAgICAgYGBgYGAgICBgYCBgYGAgYGBgICBgYCBgYGAgYGBgXpCCgMCAgICAQQFBAMEAwEBAwMDAwMCAwMDBQMCAgIAARFSgIGCgYCBgICBgIKBgYGBgYCAgYCAgICAgYCAgICAgYGBgYGBgYGBgICAgICAgICAgIGBgYGBgYGBgYGBWREDAwMCAwMDAwMDAwMDAQMEAwMCAwICAwMDAwEBAQIAAQIDJ3CAgYCAgYCAgICCgYGCgYCAgYCAgICAgYCAgICAgIGBgYCAgIGBgYCAgIGAgICAgICBgYGBgIGBgXEiAwMDAwMDAwIDAwMDAwMBAQMDAwIDAgMDAwMDAwUEAwIBAgEBAAFBgICAgYGAgICAgIGBgYGAgICAgICBgICAgX+AgYGAgIGAgIGCgYCAgICAgYCAgICBgYGBgYGBSgoDAwMDAwMDAwMDAwUDAQMBAQEBBAMDAwIDAwMDAwMEAwMAAgABAQEAGHCBgYGAgICAgIGBgYCBgYGAgYCBgICBgYCBgoGAgICAgICBgYCAgICBgYCAgICBgYGBgXEiAwMDAwMDAwMDAwMDAwQDAwMBAQEBAwMDAwMDAwMDBAICAwIAAQMBAAADARBQgYCAgIGBgIGBgYGAgICAgYCBgICAgYCCgIGAgICAgYCBgYCAgICBgYCAgICBgYGBWQoDAwMDAwMDAwMDAwMDAwQDAwMBAwEBAwMDAwMDAwMDAwMDAwIBAQEBAgEDAgEDQYGBgYGCgYGBgYGAgICAgYKBgICAgYGBgYGAgICBgYGAgYGBgIGBgYCAgICBgYE4AwMDAwMDAwMDAwIDAwMDAwMEAwEBAQEBAwIDAgMDBQMDAwMDAgMCAgMDAgMBAwECAiF4gYCBgYKBgICAgICAgYGBgIGAgYCAgIGBgYCBgYGAgICAgYCAgICBgICAeCEDAQMDAwMDAwMDAwIDAwMDAwQEBAMDAwMDAwMCAwMDAwMDBAMDAwMDAwMDAQIBAwIDAwMTcICBgYCBgIGBgICAgYGBgYCBgYCAgIGBgICAgYGAgICAgICAgYGBgIBxEAMDAwMDAwMDAwMDBQMDAwMDAwMDBAMDAwQDBAMDAwMDAwMDAwMDAwMDAQMDAwQDAwMDAwMDEXCBgICBgYGBgIGAgYGAgYGAgYGBgYGBgYCBgIGAgIGBgICBgYGBgHARAgIDAQIDAwMDBQMDBQMDBQMDAwMEAwEDAQEBAwMCAwMDAwMEBAIDAwIDAgEDBAMEAwMDAgMDAxFwgYGBgYGBgoCAgIGBgYKBgYKBgoKAgYCBgICAgYGBgICBgYGBaBEDAwMEAwMDAwMDAwMEAwQDAwMDAQMEAQIBAQEBAwMDAwMDAwMEBQIDAwECAgMEAwMDAwMDAwMEBAIJaYGBgYGBgYGAgICBgYKBgYGBgYGBgICAgICBgYGBgICBgIFwCgMBAwMBAgMAAgMDAwMDAwQEAwEDAwQFAgMCAQICBAMDAwMDAwMDBAMDAgQCAQMDAwMDAwMDAwECAwMDEnGBgYGBgYGAgIGBgYGBgYGBgIGAgICBgIGCgYCAgIGBgHASBAEDAwMEAwMDAwEDBAMBAwQDAwMDBAQDAwEDAQECAwMDAwIDAgMDAwICAgEBAQMDAwICAgMDAwMBAwMDAxJxgoGBgYGAgIGBgYCAgICBgICAgIGAgYGCgYGBgICCcRIBAQQDAwMDAwMCAwIFBAMEAwEDAwMDAwQEAwMEAwECAwMDAwMCAgICAwIAAQEBAQEDAQMCAwMDBAMDAwMDBAMReIGBgYGCgYGBgYCAgICBgYCAgICAgYGBgYKBgYF5EgMDAwMBAwIDAwMDAwMDAgMCAwMDBAUFBAMEAwQDAwEBAwQDBAIEAgICAgICAgIBAQIDAwMDAwMFAwMDAwMDAgMBIIGAgICBgYCBgICAgICAgYGAgICBgYGCgYGBgIEjBQUDAwMDAQMBAwQBAwQDAwMDAwMDAgMBAwMDBAMDAwEBAwMDAwMDAgICAgMBAgACAgIDAQMDAwQFBQIEAwMCAwICATiAgICBgICBgYCAgIGAgYGBgYGAgYGBgYGBgUEDBQMDAwMDAwICAwMDAwMEAwMDAwMDAgIBAgICAwMDAwICAgUDAgMDAwYCAwIDAgICAgMCAwMFBQUDAwEDAwMCAAIBAQNZgIB/gICAgYGAgYCAgIGBgoGBgYGAgICAUAECAQQDAwMCAQICAwMDAwECAwMDAwMBAwEBBAMDAwIDAwEFAwMCAwIDAwMDAwICAgMAAwMCAwQEBQUEAwMEAwMDAQMBAQMHb4CAgICBgoGBgYCAgYGBgYGBgICAgIBxEgIBAwMDBQMBAwMDAgMDAwMDAwMDAQMEAwQBAgIDAwEDAgIDAAIBBAMEAgMDAwMBAwMCAwMDAwMEBAICBAMDAwMBBAMDAwMBH4CAgIGBgIGBgYCAgYGAgYGAgYCAgYEZAwMDAwMDAwMDAwMDAgMEBAIDAgMDAwMDAwQBBAIBAQMCAwMCAQECAQIDAwQDAgICAgICAgMDAwMBAQMDAwMDAwMCAwMDAwMDAUmAgICCgIGBgYCAgYGBgYCAgICAgUICBAQDAQMEAwQEAwQEAQQBAwMDAwMDAwMCAgQDAQECAgIDAgECAgMAAwIDAwMBAwIDAgMCAgMBAwMDAwMCBQIBAwMDAgMDAwMDAQlwgIKBgIKBgYCBgYGBgYF/gICBcQQDBQQDAwMFAwEDBQMDAwMCAwMDAQQDAgIDAwMBAQECAgQFAgIEAgQCBQEDAwMBAgMEAwQDAQMDAwMEAwQDAwMCAgIDAwMDAwQDAgIhgYGBgYKBgoCBgYGBgYGBgIGBKQEBAgIDAwIDAQMCAwECAwEBAQEEAwMDAgICAgMCAwICAgIEAgQBAwUDAwMDAwMEAwEDAQEDAwQDAwMDAwMDAwIDAwMDAgIDAwABAQIBWYCAgICBgoCBgYGBgYGBgIFSAwMDAwUDAwMDAwMDBAMDAQMCAwIDAwQEBAEBAQEDAwMDAwMDAgIBAwUDAwIBAwMDBAEBAQEEAwQFAwIDAwMDAwEDBQMDAgIDAwQDAQICEXeAgICAgYGBgoKBgYGBgYERAwMDAQMCAwMFAwMBBAIFAwECAgIDAwIEBAQBAQEDAgMDAwMDAwIBAgQEAwIDAwMDBQMDBAQDAQMCAgMCAwIBAQMDAgEDAwMDAwMEAwMDA0CAgICAgIGCgYGBgYKBgVEEAwMDAwQDAwIDAgMBAwECAgIDAwIDBAMDAwICAwMDAwMDAgMEAgQEAwMDAwMDBAMEBAIDAwQBAwECAAEBAwEDAQIDAwIDAwMDAwUEAwMDAwl4gICCgYCBgoGBgYGBcRMDAwUEBAMDAwEDAwMBAQUDAwUDAgIDAwIDAwMDAwIDAwMDAwMBAwQEAwMDBAIDAwMCAgMDAQMBAQICAAMCAwABAQEBAQEBAQMDAwMDAwMDAwJBgYGAgYCBgYGAgYGBQAMFBQQDBAMCAgMDAgUDAwMBAwMDAwICAwMDAwMDAwMDAgQEAwMEAwEBAwMDAwMDAwMDBQEBAQEBAQMBAQIBAwMBAwMDAQEBAQMDAwMDBQQDAwIKeIGBgYCBgYGAgIGBEwIEBQQDAwMDAQEDBAMDBAEDAwMDAwICAgMDAwMDAwIDAwMDAgMDAwICAwMDAgMDAwMEAQEBAQECAgEDAgEBAwMBAgMDAwEBAQIDAwMDAwMDAwICQoGAgYCBgYCBgIFSBAQDAwMDBAMEAwEDAgABAwEBAwICAwMEAgIDAwMDAwMDAwMFAwMDAwECAwMCAgEDAwMFAwMDAAIDAAIDAgEDBQMBAwIAAgMBAQIDAwMDAwMDAgICEYGBgYGBgYGBgYESAwQEAwUDAwUDAwMBAQIDAgEBAQMBAwMCAgMDAwMDAwMEAgIDAwMDAwICAwMBAwMBAQMDAwMDAQEDAQECAQEDAwICAwMBAQMCAAICAwMDAwMDAwMDAmCAgIGBgYGAgVgEAwMEBAQDBQUEAwEDAgMCAgEDAQMCAQMCBAMBAwMDAwMCAgIEAgIDAgECAwMEAwMDAwMDAwMDAQEBAgEBAQMDAwMDAwMBAgEBAQIDAQEDAwMDAwMDASCAgIGBgYKAgSkDAwECAwUBAwMDAwUEAQEAAQECAQQAAQIEAwICAQMDAwMDAwICAgICAgICAwMBAQEDBQMBAgMDAQEBAwEBAQIBAQEDAgMCAgEBAgIEAwQDAwMDAwIFAwN5gYGBgYKBcAQDAwMDBAIDAwMDAwUEAQABAQEBAQEDAwEBAwECAwICAwICAwICAgEDAgEBAwUBBAMFBQQDAwMDAgICAwADAwEBAQQBAwEBAQMBAQEDAwMDAwMDBQMDAwJKgYGBgYGBUgQEAwMFAwMDAwMDAQQEAQEBBAECAQEDBQQEAQECBAQCAwQBBQIDAwMCAgIBAwMDBAMDAwMDAwMDAQMBAQECAQEDAgEDAwEAAQICAgIBAwQDAgIDAgMDAwMigYGBgIGAIQIEAQMEAwMDBAQDAQEDAQEBAQEBAQMBAwEBAQEFAQEAAQEBAQACAQEDAwIBAwMDAwIDBAMEAwMFAwMCAwMCAAEDAwACAwEBAQEDAQIBAQIDAQMCAwMCAwMCeYCBgYFxAgMDAwMDAwUEBAQBAQMBAQEBAQEAAAMBAQECAgEBAgEBAQIAAQEBAQIDAgMBAwMDAwMDAwMBAwMDAwMDAwMBAQUBAwEBAgMCAgEBAwMDAgACAgMDAwMDAwMCUYGBgYBPAgMFBAEDBAMEBQEBAQMDBQQBBAEBAgQFAgEFAgIAAQECAgIBAQEDAQMBAQECAwMBAwEDAQEDAQMDAgMDAwMAAQMBAQABAQECAgEDAwMDAgEBAwMDAgMDAwMDMIGBgYEpAwMEAwEDAwMEAwIEBAEBBAMBAwEBAwEDAwECAQIBAQECAgEBAQEBAQEBAQEBAgMDAQEDAwMDAwQDAwMDAwMDAwIDAQEDAQEDAwMDAwMDBAMDAwMDBAMDAwEBCYCAgYERBAQEAwQCAwMBAwMCAgEBAQEBAQIBAQEAAQECAgICAQEDAwMDAwEBAQQBAQABAwMDAwEDAwMCAwMDAwUBAwIDAAIBAgMBAQICAwIDAwEBAwMDAgMDAwMDAwMCAzlweTkDAwMDAgEDAwEEAwEEAgIBAQEBAQACAwEBAQEBAgQBAQECAwMDAwEBBAMBAQEB';

  let alphaMap96: Uint8Array | null = null;

  function getAlphaMap96(): Uint8Array {
    if (alphaMap96) return alphaMap96;
    const raw = atob(ALPHA_96_B64);
    alphaMap96 = new Uint8Array(raw.length);
    for (let i = 0; i < raw.length; i++) {
      alphaMap96[i] = raw.charCodeAt(i);
    }
    return alphaMap96;
  }

  function getScaledAlpha(alpha96: Uint8Array, targetSize: number): Uint8Array {
    if (targetSize === 96) return alpha96;
    const scale = 96 / targetSize;
    const out = new Uint8Array(targetSize * targetSize);
    for (let y = 0; y < targetSize; y++) {
      for (let x = 0; x < targetSize; x++) {
        const sx = Math.min(95, Math.floor(x * scale));
        const sy = Math.min(95, Math.floor(y * scale));
        out[y * targetSize + x] = alpha96[sy * 96 + sx];
      }
    }
    return out;
  }

  export interface WatermarkRegion {
    x: number;
    y: number;
    w: number;
    h: number;
  }

  export function getWatermarkRegion(W: number, H: number): WatermarkRegion {
    const large = Math.max(W, H) > 1024;
    const wmSize = large ? 96 : 48;
    const padding = large ? 64 : 32;
    return {
      x: W - wmSize - padding,
      y: H - wmSize - padding,
      w: wmSize,
      h: wmSize,
    };
  }

  export function removeGeminiWatermark(canvas: HTMLCanvasElement): boolean {
    const ctx = canvas.getContext('2d');
    if (!ctx) return false;

    const W = canvas.width;
    const H = canvas.height;
    const wm = getWatermarkRegion(W, H);

    if (wm.x < 0 || wm.y < 0 || wm.x + wm.w > W || wm.y + wm.h > H) {
      console.warn('[WatermarkOff] Region out of bounds', { W, H, wm });
      return false;
    }

    console.log('[WatermarkOff] Image:', W, '\u00d7', H,
      '| Region:', wm.w + '\u00d7' + wm.h + ' at (' + wm.x + ', ' + wm.y + ')');

    const alpha96 = getAlphaMap96();
    const alphaMap = getScaledAlpha(alpha96, wm.w);

    const regionData = ctx.getImageData(wm.x, wm.y, wm.w, wm.h);
    const px = regionData.data;

    let pixelsFixed = 0;

    for (let y = 0; y < wm.h; y++) {
      for (let x = 0; x < wm.w; x++) {
        const ai = alphaMap[y * wm.w + x];
        if (ai < 3) continue;

        const a = ai / 255;
        const denom = 1 - a;
        const idx = (y * wm.w + x) * 4;

        for (let ch = 0; ch < 3; ch++) {
          const blended = px[idx + ch];
          const original = (blended - 255 * a) / denom;
          px[idx + ch] = Math.max(0, Math.min(255, Math.round(original)));
        }
        pixelsFixed++;
      }
    }

    ctx.putImageData(regionData, wm.x, wm.y);

    console.log('[WatermarkOff] Reverse alpha blending applied \u2014', pixelsFixed, 'pixels restored');
    console.log('[WatermarkOff] Done');
    return true;
  }
  